"""Public domain contracts and deterministic lifecycle rules."""

from .enums import (
    AvailabilityStatus,
    CandidateReviewAction,
    EvidenceClaimType,
    EvidenceConfidence,
    SearchSourceType,
    SourceKind,
    SupervisorLifecycleStatus,
    VerificationStatus,
)
from .lifecycle import (
    CandidateApprovalRequiredError,
    CandidateReviewScopeError,
    InvalidSupervisorTransitionError,
    SupervisorVerificationError,
    apply_candidate_review,
    create_supervisor_shortlist,
    is_structural_transition_allowed,
    structurally_allowed_transitions,
    validate_structural_transition,
    verify_supervisor,
)
from .models import (
    CandidatePreferenceRevision,
    CandidateProfile,
    CandidateReviewDecision,
    EvidenceClaim,
    PlannedSearchQuery,
    ProspectiveSupervisor,
    ResearchFitAssessment,
    ResearchFitBreakdown,
    ResearchFitEvidenceError,
    SearchPlan,
    SupervisorShortlist,
    VerifiedSupervisor,
    derive_availability_status,
    missing_verification_evidence,
    validate_research_fit_evidence,
)

__all__ = [
    "AvailabilityStatus",
    "CandidateApprovalRequiredError",
    "CandidatePreferenceRevision",
    "CandidateProfile",
    "CandidateReviewAction",
    "CandidateReviewDecision",
    "CandidateReviewScopeError",
    "EvidenceClaim",
    "EvidenceClaimType",
    "EvidenceConfidence",
    "SearchSourceType",
    "InvalidSupervisorTransitionError",
    "ProspectiveSupervisor",
    "PlannedSearchQuery",
    "ResearchFitAssessment",
    "ResearchFitBreakdown",
    "SearchPlan",
    "SourceKind",
    "SupervisorLifecycleStatus",
    "SupervisorShortlist",
    "SupervisorVerificationError",
    "VerificationStatus",
    "VerifiedSupervisor",
    "apply_candidate_review",
    "create_supervisor_shortlist",
    "derive_availability_status",
    "is_structural_transition_allowed",
    "missing_verification_evidence",
    "ResearchFitEvidenceError",
    "structurally_allowed_transitions",
    "validate_research_fit_evidence",
    "validate_structural_transition",
    "verify_supervisor",
]
