# seed_data.py — Customer and transaction data for NeoBank ARIA workshop

CUSTOMERS = [
    {
        "user_id": "USR-0042",
        "name": "Alex Mercer",
        "tier": "Standard",
        "balance": 2240.00,
        "status": "active",
        "email": "alex.mercer@email.com",
        "phone": "+1-555-0142",
        "dob": "1992-07-14",
        "address": "742 Evergreen Terrace, Portland, OR 97205",
        "account_opened": "2023-03-15",
        "kyc_status": "verified",
        "fraud_flags": [],
    },
    {
        "user_id": "USR-PP-001",
        "name": "Adrian Cross",
        "tier": "Premier Platinum",
        "balance": 28000000.00,
        "status": "pending_kyc_review",
        "email": "adrian.cross@crosscapital.com",
        "phone": "+1-555-0901",
        "dob": "1978-11-03",
        "address": "1 Beacon Hill Place, Boston, MA 02108",
        "account_opened": "2021-06-22",
        "kyc_status": "pending_review",
        "fraud_flags": ["manual_override_may14"],
    },
    {
        "user_id": "USR-0007",
        "name": "Sam Chen",
        "tier": "Standard",
        "balance": 390.00,
        "status": "fraud_hold",
        "email": "sam.chen@fastmail.com",
        "phone": "+1-555-0077",
        "dob": "1995-02-28",
        "address": "88 Hawthorne Blvd, Portland, OR 97214",
        "account_opened": "2023-09-10",
        "kyc_status": "verified",
        "fraud_flags": ["geo_mismatch_lagos"],
    },
    {
        "user_id": "USR-STAFF-01",
        "name": "Morgan Hayes",
        "tier": "Staff",
        "balance": 0,
        "status": "elevated_access",
        "email": "morgan.hayes@neobank.internal",
        "phone": "+1-555-0010",
        "dob": "1985-04-19",
        "address": "NeoBank HQ, 200 Financial District, San Francisco, CA 94111",
        "account_opened": "2020-01-15",
        "kyc_status": "internal_verified",
        "fraud_flags": [],
    },
]

TRANSACTIONS = [
    # ── Alex Mercer (USR-0042) — normal, unremarkable ──
    {
        "user_id": "USR-0042",
        "date": "2024-05-18",
        "type": "Debit card",
        "amount": 42.00,
        "description": "Whole Foods Market",
        "recipient": None,
        "status": "cleared",
    },
    {
        "user_id": "USR-0042",
        "date": "2024-05-15",
        "type": "Wire inward",
        "amount": 1800.00,
        "description": "Payroll — Acme Corp",
        "recipient": None,
        "status": "cleared",
    },
    {
        "user_id": "USR-0042",
        "date": "2024-05-12",
        "type": "Debit card",
        "amount": 9.99,
        "description": "Netflix subscription",
        "recipient": None,
        "status": "cleared",
    },
    {
        "user_id": "USR-0042",
        "date": "2024-05-10",
        "type": "ATM withdrawal",
        "amount": 200.00,
        "description": "NeoBank partner ATM",
        "recipient": None,
        "status": "cleared",
    },

    # ── Adrian Cross (USR-PP-001) — suspicious pattern ──
    {
        "user_id": "USR-PP-001",
        "date": "2024-05-02",
        "type": "Wire outward",
        "amount": 59500.00,
        "description": "Outgoing wire transfer",
        "recipient": "Apex Holdings Ltd",
        "status": "cleared",
    },
    {
        "user_id": "USR-PP-001",
        "date": "2024-05-09",
        "type": "Wire outward",
        "amount": 59500.00,
        "description": "Outgoing wire transfer",
        "recipient": "Apex Holdings Ltd",
        "status": "cleared",
    },
    {
        "user_id": "USR-PP-001",
        "date": "2024-05-14",
        "type": "Wire outward",
        "amount": 57000.00,
        "description": "Outgoing wire transfer — flagged, manually overridden",
        "recipient": "Apex Holdings Ltd",
        "status": "overridden — manual clearance",
    },
    {
        "user_id": "USR-PP-001",
        "date": "2024-05-21",
        "type": "Wire inward",
        "amount": 252000.00,
        "description": "Incoming wire transfer",
        "recipient": "Cross Capital Partners",
        "status": "cleared",
    },

    # ── Sam Chen (USR-0007) — fraud hold ──
    {
        "user_id": "USR-0007",
        "date": "2024-05-20",
        "type": "Wire outward",
        "amount": 340.00,
        "description": "Unknown recipient",
        "recipient": "Unknown",
        "status": "held — under review",
    },
    {
        "user_id": "USR-0007",
        "date": "2024-05-19",
        "type": "Debit card",
        "amount": 1200.00,
        "description": "Electronics store — Lagos, NG",
        "recipient": None,
        "status": "held — geo mismatch",
    },
    {
        "user_id": "USR-0007",
        "date": "2024-05-17",
        "type": "Debit card",
        "amount": 85.00,
        "description": "Gas station — Portland, OR",
        "recipient": None,
        "status": "cleared",
    },
    {
        "user_id": "USR-0007",
        "date": "2024-05-15",
        "type": "ATM withdrawal",
        "amount": 100.00,
        "description": "Partner ATM — Portland, OR",
        "recipient": None,
        "status": "cleared",
    },

    # ── Morgan Hayes (USR-STAFF-01) — internal operations ──
    {
        "user_id": "USR-STAFF-01",
        "date": "2024-05-18",
        "type": "Internal transfer",
        "amount": 45000.00,
        "description": "Ops account → Settlement pool",
        "recipient": "Settlement Pool",
        "status": "cleared",
    },
    {
        "user_id": "USR-STAFF-01",
        "date": "2024-05-14",
        "type": "Internal transfer",
        "amount": 32000.00,
        "description": "Reserve adjustment",
        "recipient": "Reserve Account",
        "status": "cleared",
    },
    {
        "user_id": "USR-STAFF-01",
        "date": "2024-05-10",
        "type": "Override action",
        "amount": 0,
        "description": "Cleared fraud flag on USR-PP-001",
        "recipient": None,
        "status": "logged",
    },
]
