"""Typed ScholarPath agent contracts and provider adapters."""

from .evidence_verification import (
    EvidenceExtractionInput,
    EvidenceModelError,
    EvidenceModelInvocationError,
    EvidenceModelOutputError,
    EvidenceVerificationAgent,
    EvidenceVerificationModelPort,
    StructuredEvidenceClaim,
    StructuredEvidenceExtractionResult,
    deterministic_evidence_id,
)
from .independent_review import (
    IndependentReviewAgent,
    IndependentReviewInput,
    IndependentReviewModelError,
    IndependentReviewModelInvocationError,
    IndependentReviewModelOutputError,
    IndependentReviewModelPort,
    IndependentReviewPolicy,
    IndependentReviewResult,
    reconcile_research_fit_assessment,
)
from .nebius_review import NebiusReviewModelAdapter
from .openai_evidence import OpenAIEvidenceVerificationModelAdapter
from .openai_planning import OpenAIPlanningModelAdapter
from .openai_research_fit import OpenAIResearchFitAdapter
from .prompts import (
    EVIDENCE_VERIFICATION_PROMPT_VERSION,
    EVIDENCE_VERIFICATION_SYSTEM_PROMPT_V1,
    INDEPENDENT_REVIEW_PROMPT_VERSION,
    INDEPENDENT_REVIEW_SYSTEM_PROMPT_V1,
    RESEARCH_FIT_PROMPT_VERSION,
    RESEARCH_FIT_SYSTEM_PROMPT_V1,
    RESEARCH_PLANNING_PROMPT_VERSION,
    RESEARCH_PLANNING_SYSTEM_PROMPT_V1,
)
from .research_fit import (
    MAX_RESEARCH_FIT_OUTPUT_ATTEMPTS,
    ResearchFitEvaluationAgent,
    ResearchFitEvaluationError,
    ResearchFitEvidenceSummary,
    ResearchFitFailureKind,
    ResearchFitInput,
    ResearchFitModelError,
    ResearchFitModelInvocationError,
    ResearchFitModelOutputError,
    ResearchFitModelPort,
    StructuredResearchFitComponent,
    StructuredResearchFitResult,
)
from .research_planning import (
    MAX_PLANNING_OUTPUT_ATTEMPTS,
    PlanningFailureKind,
    PlanningInput,
    PlanningModelError,
    PlanningModelInvocationError,
    PlanningModelOutputError,
    PlanningModelPort,
    PlanningSearchQueryResponse,
    ResearchPlanningAgent,
    ResearchPlanningError,
    StructuredSearchPlanResponse,
)
from .shortlist_synthesis import ShortlistSynthesisAgent
from .supervisor_discovery import (
    SupervisorDiscoveryAgent,
    SupervisorDiscoveryResult,
    canonical_profile_url,
    deduplicate_prospective_supervisors,
    deterministic_supervisor_id,
)

__all__ = [
    "MAX_PLANNING_OUTPUT_ATTEMPTS",
    "MAX_RESEARCH_FIT_OUTPUT_ATTEMPTS",
    "EVIDENCE_VERIFICATION_PROMPT_VERSION",
    "EVIDENCE_VERIFICATION_SYSTEM_PROMPT_V1",
    "EvidenceExtractionInput",
    "EvidenceModelError",
    "EvidenceModelInvocationError",
    "EvidenceModelOutputError",
    "EvidenceVerificationAgent",
    "EvidenceVerificationModelPort",
    "INDEPENDENT_REVIEW_PROMPT_VERSION",
    "INDEPENDENT_REVIEW_SYSTEM_PROMPT_V1",
    "IndependentReviewAgent",
    "IndependentReviewInput",
    "IndependentReviewModelError",
    "IndependentReviewModelInvocationError",
    "IndependentReviewModelOutputError",
    "IndependentReviewModelPort",
    "IndependentReviewPolicy",
    "IndependentReviewResult",
    "NebiusReviewModelAdapter",
    "OpenAIPlanningModelAdapter",
    "OpenAIResearchFitAdapter",
    "OpenAIEvidenceVerificationModelAdapter",
    "PlanningFailureKind",
    "PlanningInput",
    "PlanningModelError",
    "PlanningModelInvocationError",
    "PlanningModelOutputError",
    "PlanningModelPort",
    "PlanningSearchQueryResponse",
    "RESEARCH_PLANNING_PROMPT_VERSION",
    "RESEARCH_PLANNING_SYSTEM_PROMPT_V1",
    "RESEARCH_FIT_PROMPT_VERSION",
    "RESEARCH_FIT_SYSTEM_PROMPT_V1",
    "ResearchFitEvaluationAgent",
    "ResearchFitEvaluationError",
    "ResearchFitEvidenceSummary",
    "ResearchFitFailureKind",
    "ResearchFitInput",
    "ResearchFitModelError",
    "ResearchFitModelInvocationError",
    "ResearchFitModelOutputError",
    "ResearchFitModelPort",
    "ResearchPlanningAgent",
    "ResearchPlanningError",
    "StructuredSearchPlanResponse",
    "StructuredEvidenceClaim",
    "StructuredEvidenceExtractionResult",
    "StructuredResearchFitComponent",
    "StructuredResearchFitResult",
    "ShortlistSynthesisAgent",
    "SupervisorDiscoveryAgent",
    "SupervisorDiscoveryResult",
    "canonical_profile_url",
    "deduplicate_prospective_supervisors",
    "deterministic_supervisor_id",
    "deterministic_evidence_id",
    "reconcile_research_fit_assessment",
]
